//nolint:godoclint // Private product-graph vocabulary is local to certification.
package stringlanguage

import (
	"encoding/binary"
	"slices"
)

const (
	productStateBaseBytes = 48
	productEdgeBytes      = 40
)

type productTuple struct {
	patterns []uint32
	length   int
}

type productEdge struct {
	next  uint32
	bytes byteSet
}

type productState struct {
	edges     []productEdge
	accepting bool
}

type product struct {
	states   []productState
	shortest []int
	minimum  int
	maximum  *int
}

type graphBudget struct {
	limits      constructionLimits
	states      uint64
	transitions uint64
	bytes       uint64
	work        uint64
}

//nolint:cyclop,gocognit // Exhaustive exploration keeps every resource check at its allocation site.
func buildProduct(
	machines []*dfa,
	requirements []Requirement,
	length Length,
	limits constructionLimits,
) (*product, error) {
	if uint64(length.Min) > limits.generatedBytes {
		return nil, limitError(
			"output", "generated bytes", limits.generatedBytes, uint64(length.Min),
		)
	}

	effectiveMaximum := length.Max
	if length.Max != nil && uint64(*length.Max) > limits.generatedBytes {
		effectiveMaximum = nil
	}

	work := &graphBudget{limits: limits}
	initial := productTuple{patterns: make([]uint32, len(machines))}
	tuples := []productTuple{initial}
	keys := map[string]uint32{productKey(initial): 0}
	graph := &product{minimum: length.Min, maximum: length.Max}

	if err := work.addState(len(machines)); err != nil {
		return nil, err
	}

	graph.states = append(graph.states, productState{
		accepting: productAccepts(initial, machines, requirements, length.Min, effectiveMaximum),
	})

	for current := 0; current < len(tuples); current++ {
		tuple := tuples[current]
		if effectiveMaximum != nil && tuple.length == *effectiveMaximum {
			continue
		}

		if err := work.addTransitions(asciiAlphabetSize); err != nil {
			return nil, err
		}

		if err := work.addCertificationWork(asciiAlphabetSize); err != nil {
			return nil, err
		}

		byTarget := make(map[uint32]byteSet)

		for value := range asciiAlphabetSize {
			next := productTuple{
				patterns: make([]uint32, len(machines)),
				length:   nextLength(tuple.length, length.Min, effectiveMaximum),
			}
			for index, machine := range machines {
				next.patterns[index] = machine.states[tuple.patterns[index]].transitions[value]
			}

			key := productKey(next)

			nextID, ok := keys[key]
			if !ok {
				nextID = uint32(len(tuples))
				if err := work.addState(len(machines)); err != nil {
					return nil, err
				}

				keys[key] = nextID

				tuples = append(tuples, next)
				graph.states = append(graph.states, productState{
					accepting: productAccepts(next, machines, requirements, length.Min, effectiveMaximum),
				})
			}

			set := byTarget[nextID]
			set.add(byte(value))
			byTarget[nextID] = set
		}

		targets := make([]uint32, 0, len(byTarget))
		for target := range byTarget {
			targets = append(targets, target)
		}

		slices.Sort(targets)

		if err := work.addGraphBytes(uint64(len(targets)) * productEdgeBytes); err != nil {
			return nil, err
		}

		graph.states[current].edges = make([]productEdge, 0, len(targets))
		for _, target := range targets {
			graph.states[current].edges = append(graph.states[current].edges, productEdge{
				next: target, bytes: byTarget[target],
			})
		}
	}

	if err := graph.certify(work); err != nil {
		return nil, err
	}

	if graph.shortest[0] < 0 {
		return nil, &EmptyError{}
	}

	if uint64(graph.shortest[0]) > limits.generatedBytes {
		return nil, limitError(
			"output",
			"generated bytes",
			limits.generatedBytes,
			uint64(graph.shortest[0]),
		)
	}

	return graph, nil
}

//nolint:cyclop // Reverse reachability and shortest-distance certification are one atomic proof.
func (graph *product) certify(work *graphBudget) error {
	reverse := make([][]uint32, len(graph.states))
	for source, state := range graph.states {
		for _, edge := range state.edges {
			if err := work.addCertificationWork(1); err != nil {
				return err
			}

			reverse[edge.next] = append(reverse[edge.next], uint32(source))
		}
	}

	graph.shortest = make([]int, len(graph.states))
	for index := range graph.shortest {
		graph.shortest[index] = -1
	}

	queue := make([]uint32, 0)

	for state, item := range graph.states {
		if !item.accepting {
			continue
		}

		if err := work.addCertificationWork(1); err != nil {
			return err
		}

		graph.shortest[state] = 0
		queue = append(queue, uint32(state))
	}

	for head := 0; head < len(queue); head++ {
		state := queue[head]
		for _, predecessor := range reverse[state] {
			if err := work.addCertificationWork(1); err != nil {
				return err
			}

			if graph.shortest[predecessor] >= 0 {
				continue
			}

			graph.shortest[predecessor] = graph.shortest[state] + 1
			queue = append(queue, predecessor)
		}
	}

	return nil
}

func (graph *product) matches(value string) bool {
	if firstNonASCII(value) >= 0 || len(value) < graph.minimum ||
		graph.maximum != nil && len(value) > *graph.maximum {
		return false
	}

	state := uint32(0)

	for index := range len(value) {
		matched := false

		for _, edge := range graph.states[state].edges {
			if edge.bytes.contains(value[index]) {
				state = edge.next
				matched = true

				break
			}
		}

		if !matched {
			return false
		}
	}

	return graph.states[state].accepting
}

func productAccepts(
	tuple productTuple,
	machines []*dfa,
	requirements []Requirement,
	minLength int,
	maxLength *int,
) bool {
	if tuple.length < minLength || maxLength != nil && tuple.length > *maxLength {
		return false
	}

	for index, machine := range machines {
		if machine.states[tuple.patterns[index]].accepting != requirements[index].WantMatch {
			return false
		}
	}

	return true
}

func nextLength(current int, minLength int, maxLength *int) int {
	if maxLength != nil {
		return current + 1
	}

	if current >= minLength {
		return minLength
	}

	return current + 1
}

func productKey(tuple productTuple) string {
	key := binary.AppendUvarint(nil, uint64(tuple.length)+1)
	for _, state := range tuple.patterns {
		key = binary.AppendUvarint(key, uint64(state)+1)
	}

	return string(key)
}

func (work *graphBudget) addState(patterns int) error {
	if err := addLimited(
		&work.states,
		1,
		work.limits.productStates,
		"product construction",
		"reachable product states",
	); err != nil {
		return err
	}

	return work.addGraphBytes(productStateBaseBytes + uint64(patterns)*4)
}

func (work *graphBudget) addTransitions(amount uint64) error {
	return addLimited(
		&work.transitions,
		amount,
		work.limits.productTransitions,
		"product construction",
		"reachable product transitions",
	)
}

func (work *graphBudget) addGraphBytes(amount uint64) error {
	return addLimited(
		&work.bytes,
		amount,
		work.limits.graphBytes,
		"product construction",
		"graph bytes",
	)
}

func (work *graphBudget) addCertificationWork(amount uint64) error {
	return addLimited(
		&work.work,
		amount,
		work.limits.certificationWork,
		"certification",
		"certification work",
	)
}

func addLimited(
	counter *uint64,
	amount uint64,
	maximum uint64,
	phase string,
	limit string,
) error {
	if amount > ^uint64(0)-*counter {
		return limitError(phase, limit, maximum, ^uint64(0))
	}

	observed := *counter + amount
	if observed > maximum {
		return limitError(phase, limit, maximum, observed)
	}

	*counter = observed

	return nil
}
